# Generated by Django 5.0.6 on 2024-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitllist', '0002_remove_enter_pho'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter',
            name='phone',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
