# Generated by Django 5.0.4 on 2024-06-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
