# Generated by Django 5.0.4 on 2024-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_doctor_patient_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
